apiVersion: v1
kind: Service
metadata:
  name: acpodnaming
  namespace: kube-acpodnaming
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: "acpodnaming-tls"
spec:
  selector:
    app: acpodnaming
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
