apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "acpodnaming.kubernetes.io" 
  annotations: 
    service.beta.openshift.io/inject-cabundle: true
webhooks:
- name: "acpodnaming.kubernetes.io"
  namespaceSelector:
    matchExpressions:
    - key: admission.kubernetes.io/podnaming
      operator: In
      values: ["True"]
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE","UPDATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "kube-acpodnaming"
      name: "acpodnaming"
      path: /validate
      port: 8443
    caBundle: 
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
